<a href="https://colab.research.google.com/github/myrondza/Data-Science-Machine-Learning-Deep-Learning-AI-Guide-Algorithms/blob/master/NLP%20-%20ELMO_Embeddings_%2B_ML_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
df = pd.read_csv("Amazon_Feedback.csv")

In [0]:
df.head(5)
df.shape

(2624, 2)

In [0]:
df.head(5)

Translated  Categorisation
0  So there is no way for me to plug it in here i...               0
1                        Good case, Excellent value.               1
2                             Great for the jawbone.               1
3  Tied to charger for conversations lasting more...               0
4                                  The mic is great.               1

In [0]:
df["Categorisation"].value_counts()

1    1312
0    1312
Name: Categorisation, dtype: int64

In [0]:

from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.3)

In [0]:
train.shape

(1836, 2)

In [0]:
test.shape

(788, 2)

In [0]:
train.head(5)

Translated  Categorisation
1692  If you own a tablet or smartphone, you already...               0
2140  This is my second Fire, I'm upgrading from the...               1
2095  Ipad killer! A fierce tablet at a convinient p...               1
1949  Amazon Fire HD8 is a great product for the pri...               1
973                                      Lousy product.               0

In [0]:
test.head(5)

Translated  Categorisation
217   I also didn't like the "on" button, it felt li...               0
1527  Not a big reader but gave it to someone that i...               0
2015  Santa dropped this off for our 4th grader alon...               1
112   its a little geeky but i think thats its sex o...               1
1542  While reading might be a bit easier on the Pap...               0

In [0]:
train.Translated = train.Translated.astype(str)
test.Translated = test.Translated.astype(str)

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [0]:
list_train = [train[i:i+100] for i in range(0,train.shape[0],100)]
list_test = [test[i:i+100] for i in range(0,test.shape[0],100)]

In [0]:
import tensorflow as tf
import tensorflow_hub as hub

elmo = hub.Module("https://tfhub.dev/google/elmo/3", trainable=True)

In [0]:
def elmo_vectors(x):
    embeddings = elmo(x.tolist(), signature="default", as_dict=True)["elmo"]

    with tf.Session().as_default() as sess:
        sess.run(tf.global_variables_initializer())
        sess.run(tf.tables_initializer())
    return sess.run(tf.reduce_mean(embeddings,1))

In [0]:
elmo_train = [elmo_vectors(x['Translated']) for x in list_train]
elmo_test = [elmo_vectors(x['Translated']) for x in list_test]

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


In [0]:
elmo_train

[array([[-0.05590973,  0.01748744, -0.05656589, ..., -0.01962131,
          0.06975626, -0.0069666 ],
        [ 0.01957587, -0.05813252, -0.03042094, ...,  0.01160928,
         -0.01087077,  0.08379146],
        [-0.030004  , -0.0823576 ,  0.04411279, ...,  0.00565171,
         -0.00604845, -0.00394651],
        ...,
        [-0.09619147, -0.05653161, -0.01758611, ..., -0.00935796,
          0.07060647,  0.08163676],
        [-0.04640515, -0.07699853,  0.04932263, ...,  0.02045876,
         -0.03245857, -0.00746718],
        [-0.12840311, -0.14131773,  0.04332799, ...,  0.00763464,
          0.08652419,  0.02425455]], dtype=float32),
 array([[-0.00555685, -0.0401374 , -0.01454472, ..., -0.04617067,
         -0.00321315,  0.02316854],
        [-0.05348006, -0.02844589,  0.03264654, ...,  0.01343619,
         -0.01785625,  0.01654674],
        [-0.0356683 , -0.04258285,  0.04371063, ...,  0.01591638,
         -0.0194643 , -0.02651281],
        ...,
        [-0.00915913, -0.02913946,  0.0

In [0]:
elmo_test

[array([[-0.05326062, -0.06124051,  0.04537567, ...,  0.00742864,
          0.02900877,  0.00483274],
        [-0.06810917, -0.09128679,  0.02971454, ...,  0.01206785,
          0.04824762,  0.00877706],
        [ 0.0160447 , -0.02611344,  0.00804006, ..., -0.00463661,
         -0.01888676,  0.03733744],
        ...,
        [-0.03945666, -0.04441421,  0.03120306, ...,  0.02430628,
          0.00561232,  0.00195314],
        [-0.05151843, -0.04660274,  0.02820182, ...,  0.01540758,
          0.02060791, -0.00421001],
        [-0.02928001, -0.04845738,  0.04182708, ...,  0.00053852,
         -0.03154545, -0.0025092 ]], dtype=float32),
 array([[-0.03629624, -0.04941849,  0.02975987, ...,  0.02533332,
         -0.00616744, -0.00125148],
        [-0.03266003, -0.03854065,  0.03651969, ...,  0.02401906,
         -0.0126849 , -0.01374952],
        [-0.03083234, -0.04788613,  0.03997696, ...,  0.02388266,
         -0.00704781, -0.00881144],
        ...,
        [-0.0160342 , -0.0458023 ,  0.0

In [0]:
print(len(elmo_train))
print(len(elmo_test))

19
8


In [0]:
import numpy as np
elmo_train_new = np.concatenate(elmo_train, axis = 0)
elmo_test_new = np.concatenate(elmo_test, axis = 0)

print(len(elmo_train_new))
print(len(elmo_test_new))

1836
788


In [0]:
print(len(train['Categorisation']))
print(len(test['Categorisation']))

1836
788


In [0]:
df.shape

(2624, 2)

In [0]:
import pickle
pickle_out = open("elmoemb_train.pickle","wb")
pickle.dump(elmo_train_new, pickle_out)
pickle_out.close()

# save elmo_test_new
pickle_out = open("elmoemb_test.pickle","wb")
pickle.dump(elmo_test_new, pickle_out)
pickle_out.close()

In [0]:
import pickle
pickle_in = open("elmoemb_train.pickle", "rb")
elmo_train_new = pickle.load(pickle_in)

# load elmo_train_new
pickle_in = open("elmoemb_test.pickle", "rb")
elmo_test_new = pickle.load(pickle_in)

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(elmo_train_new, 
                                                  train['Categorisation'],  
                                                  random_state=42, 
                                                  test_size=0.3)

In [0]:
print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)

(1285, 1024) (551, 1024) (1285,) (551,)


# Decision Tree

In [0]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix 

dtree = DecisionTreeClassifier()
pipeline = Pipeline(steps=[('dt', dtree)])


param_range = [1, 2, 3, 4, 5]

parameters = dict(dt__criterion= ['gini', 'entropy'],
dt__min_samples_leaf= param_range,
dt__max_depth= param_range,
dt__min_samples_split= param_range[1:],
dt__presort= [True, False])


dt_clf = GridSearchCV(estimator=pipeline,param_grid=parameters,scoring='accuracy',cv=5) 
dt_clf.fit(X_train, y_train)
cross_val_score(dt_clf, X_train, y_train)
print('Best Criterion:', dt_clf.best_estimator_.get_params()['dt__criterion'])
print('Best Min Sample Leaf:', dt_clf.best_estimator_.get_params()['dt__min_samples_leaf'])
print('Best Max Depth:', dt_clf.best_estimator_.get_params()['dt__max_depth'])
print('Best Min Sample Split:', dt_clf.best_estimator_.get_params()['dt__min_samples_split'])
print('Best Presort:', dt_clf.best_estimator_.get_params()['dt__presort'])

y_pred = dt_clf.predict(X_val) 
cm = confusion_matrix(y_val,y_pred)

print("Accuracy on Train Set",dt_clf.score(X_train,y_train))
print("Accuracy on Validation Set",dt_clf.score(X_val,y_val))
cm

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Best Criterion: gini
Best Min Sample Leaf: 1
Best Max Depth: 3
Best Min Sample Split: 2
Best Presort: True
Accuracy on Train Set 0.7603112840466926
Accuracy on Validation Set 0.647912885662432


array([[156, 115],
       [ 79, 201]])

In [0]:
preds_test = dt_clf.predict(elmo_test_new)  
from sklearn.metrics import accuracy_score
accuracy_score(test['Categorisation'],preds_test)

0.6459390862944162

# Naive Bayes

In [0]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix 

nb = BernoulliNB()

pipeline = Pipeline(steps=[('nb', nb)])

parameters = dict(nb__alpha= [0, 0.01, 0.05, 0.1, 0.3, 0.5])

nb_clf = GridSearchCV(estimator=pipeline,param_grid=parameters,scoring='accuracy',cv=5) 
nb_clf.fit(X_train, y_train)
cross_val_score(nb_clf, X_train, y_train)
print('Best Alpha:', nb_clf.best_estimator_.get_params()['nb__alpha'])

y_pred = nb_clf.predict(X_val) 
cm = confusion_matrix(y_val,y_pred)

print("Accuracy on Train Set",nb_clf.score(X_train,y_train))
print("Accuracy on Validation Set",nb_clf.score(X_val,y_val))
cm

/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:485: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:485: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:485: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:485: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:485: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/mod

Best Alpha: 0.01
Accuracy on Train Set 0.598443579766537
Accuracy on Validation Set 0.5916515426497277


array([[114, 157],
       [ 68, 212]])

In [0]:
preds_test = nb_clf.predict(elmo_test_new) 
from sklearn.metrics import accuracy_score
accuracy_score(test['Categorisation'],preds_test)

0.5862944162436549

# XgBoost

In [0]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, cross_val_score

xgb = XGBClassifier(learning_rate=0.02, n_estimators=10, objective='multi:softmax',
                    silent=True, nthread=1,num_class=3)

pipeline = Pipeline(steps=[('xgb', xgb)])

parameters = dict(
        xgb__min_child_weight= [1, 5, 10],
        xgb__gamma= [0.5, 1, 1.5, 2, 5],
        xgb__subsample= [0.6, 0.8, 1.0],
        xgb__colsample_bytree= [0.6, 0.8, 1.0],
        xgb__max_depth= [3, 4, 5])


xgb_clf = GridSearchCV(estimator=pipeline,param_grid=parameters,scoring='accuracy',cv=5) 
xgb_clf.fit(X_train, y_train)
cross_val_score(xgb_clf, X_train, y_train)
print('Best Mid Child Weight:', xgb_clf.best_estimator_.get_params()['xgb__min_child_weight'])
print('Best Gamma:', xgb_clf.best_estimator_.get_params()['xgb__gamma'])
print('Best Subsample:', xgb_clf.best_estimator_.get_params()['xgb__subsample'])
print('Best Col Sample By tree:', xgb_clf.best_estimator_.get_params()['xgb__colsample_bytree'])
print('Best Max Depth:', xgb_clf.best_estimator_.get_params()['xgb__max_depth'])

y_pred = xgb_clf.predict(X_val) 
cm = confusion_matrix(y_val,y_pred)

print("Accuracy on Train Set",xgb_clf.score(X_train,y_train))
print("Accuracy on Validation Set",xgb_clf.score(X_val,y_val))
cm

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best Mid Child Weight: 5
Best Gamma: 5
Best Subsample: 0.6
Best Col Sample By tree: 0.6
Best Max Depth: 5
Accuracy on Train Set 0.9190661478599221
Accuracy on Validation Set 0.7713248638838476


array([[204,  67],
       [ 59, 221]])

In [0]:
preds_test = xgb_clf.predict(elmo_test_new) 
from sklearn.metrics import accuracy_score
accuracy_score(test['Categorisation'],preds_test)

0.7753807106598984