<a href="https://colab.research.google.com/github/myrondza/Data-Science-Machine-Learning-Deep-Learning-AI-Guide-Algorithms/blob/master/Deep_Learning_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Algorithms

## Frameworks 

### Tensorflow

What is Tensorflow?

TensorFlow is an end-to-end open source platform for machine learning

TensorFlow makes it easy for beginners and experts to create machine learning models. See the sections below to get started.

#### Importing Library

In [0]:
#!pip install tensorflow==2.0.0b1
import tensorflow as tf
print(tf.__version__)

2.0.0-beta1


#### Eager Mode

In [0]:
# The Code Compiles and will be executed in eager mode

h=tf.constant("Hello")
w=tf.constant("World")

tf.strings.join([h,w])

<tf.Tensor: id=2, shape=(), dtype=string, numpy=b'HelloWorld'>

#### Graph Mode

In [0]:
# The Code Compiles inside the Function (@tf.function) into graph code before it is executed

import tensorflow as tf
h=tf.constant("Hello")
w=tf.constant("World")


@tf.function
def concat(x,y):
    hw = x + y
    return hw

print(concat(h,w))

tf.Tensor(b'HelloWorld', shape=(), dtype=string)


In [0]:
# The Code Compiles and will not be executed in graph mode
def concat(x,y):
    hw = x + y
    return hw

print(concat(h,w))

tf.Tensor(b'HelloWorld', shape=(), dtype=string)


In [0]:
W = tf.Variable(tf.zeros(shape=(2,2)), name="W")
b = tf.Variable(tf.ones(shape=(2)), name="b")

@tf.function
def forward(x):
    return W * x + b

output = forward([1,0])
print(output)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [0]:
W = tf.Variable(1, name="W")
b = tf.Variable(5, name="b")

@tf.function
def forward(x):
    return W * x + b

output = forward(4)
print(output)

tf.Tensor(9, shape=(), dtype=int32)


In [0]:
W.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [0]:
r1 = tf.reshape(W,[1,4])

In [0]:
r1.numpy()

array([[0., 0., 0., 0.]], dtype=float32)

### Pytorch

What  is Pytorch?

It’s a Python-based scientific computing package targeted at two sets of audiences:

A replacement for NumPy to use the power of GPUs
a deep learning research platform that provides maximum flexibility and speed

In [0]:
from __future__ import print_function
import torch

In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[3.7127e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3183, 0.0442, 0.3516],
        [0.9268, 0.0550, 0.2144],
        [0.8796, 0.3361, 0.6043],
        [0.6161, 0.7851, 0.8815],
        [0.2953, 0.3483, 0.0673]])


In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = x.new_ones(5, 3, dtype=torch.double)    
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [0]:
x = torch.randn_like(x, dtype=torch.float) 
print(x)

tensor([[ 0.0069, -0.2150,  0.8116],
        [-0.4522,  1.1726, -0.3885],
        [-0.1883, -1.3238,  1.5475],
        [ 1.6086, -0.4931,  0.2757],
        [-0.3276, -0.2421,  0.5482]])


In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8492, 1.1307, 1.0533],
        [0.6561, 0.8633, 1.4646],
        [0.9527, 1.4221, 1.1873],
        [1.7161, 1.5844, 1.0095],
        [0.4096, 1.1961, 1.3020]])


In [0]:
print(torch.add(x, y))

tensor([[0.8492, 1.1307, 1.0533],
        [0.6561, 0.8633, 1.4646],
        [0.9527, 1.4221, 1.1873],
        [1.7161, 1.5844, 1.0095],
        [0.4096, 1.1961, 1.3020]])


In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8492, 1.1307, 1.0533],
        [0.6561, 0.8633, 1.4646],
        [0.9527, 1.4221, 1.1873],
        [1.7161, 1.5844, 1.0095],
        [0.4096, 1.1961, 1.3020]])


Resizing: If you want to resize/reshape tensor, you can use torch.view :

In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
device = torch.device("cuda")          # a CUDA device object
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
print(z)
print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 0.4023,  1.3189,  1.7710,  1.6037],
        [-0.2375,  1.5496,  0.9762,  1.9441],
        [-0.7012, -1.6130,  1.1936, -0.2889],
        [-0.1726,  0.5142,  0.8320,  2.0435]], device='cuda:0')
tensor([[ 0.4023,  1.3189,  1.7710,  1.6037],
        [-0.2375,  1.5496,  0.9762,  1.9441],
        [-0.7012, -1.6130,  1.1936, -0.2889],
        [-0.1726,  0.5142,  0.8320,  2.0435]], dtype=torch.float64)


In [0]:
x = torch.empty(1,5)
x = x.new_ones(1,5,requires_grad=True)
print(x)

tensor([[1., 1., 1., 1., 1.]], requires_grad=True)


In [0]:
y = x + 2
print(y)

tensor([[3., 3., 3., 3., 3.]], grad_fn=<AddBackward0>)


In [0]:
print(y.grad_fn)

In [0]:
z = y.mean()
print(z)
print(z.backward())

tensor(3., grad_fn=<MeanBackward0>)
None


In [0]:
print(x.grad)

tensor([[0.4000, 0.4000, 0.4000, 0.4000, 0.4000]])


## Neural Networks (Layers , Activation Functions , Optimizers)

### Vanishing Gradients Problem 

What Are Vanishing Gradients?

The vanishing gradients problem is one example of unstable behavior that you may encounter when training a deep neural network.

It describes the situation where a deep multilayer feed-forward network or a recurrent neural network is unable to propagate useful **gradient information** from the **output end** of the model back to the layers near the **input end** of the model.

A problem with training networks with many layers (e.g. deep neural networks) is that the gradient diminishes dramatically as it is propagated backward through the network.

The error may be so small by the time it reaches layers close to the input of the model that it may have **very little effect**

Deep models using the hyperbolic tangent activation function do not train easily, and much of this poor performance is blamed on the vanishing gradient problem.

Deep models using the **hyperbolic tangent activation function** do not train easily, and much of this **poor performance** is blamed on the vanishing gradient problem.
The number of hidden layers can be increased from 1 to 5


How to Fix Vanishing Gradients?

1) When using the **rectified linear activation** function (ReLU), it is good practice to use the He weight initialization scheme. We can define the MLP with five hidden layers using ReLU and He initialization, listed below.

2 ) This is because the activation function looks and acts like a linear function, making it easier to train and less likely to saturate, but is, in fact, a nonlinear function, forcing negative inputs to the value 0. It is claimed as one possible approach to addressing the vanishing gradients problem when training deeper models.

### Exploding Gradients Problem 

What Are Exploding Gradients?

An **error gradient** is the **direction and magnitude calculated** during the training of a neural network that is used to update the network **weights** in the right direction and by the right amount.

In deep networks or recurrent neural networks, **error gradients can accumulate** during an update and result in very large gradients. These in turn result in large updates to the network weights, and in turn, an **unstable network**.

At an extreme, the values of weights can become so large as to overflow and result in **NaN values**.

The explosion occurs through exponential growth by repeatedly multiplying gradients through the network layers that have values larger than 1.0.

How do You Know if You Have Exploding Gradients?

There are some subtle signs that you may be suffering from exploding gradients during the training of your network, such as:

1) The model is unable to get traction on your training data (e.g. poor loss).

2) The model is unstable, resulting in large changes in loss from update to update.

3) The model loss goes to NaN during training.

How to Fix Exploding Gradients?

1. Re-Design the Network Model

In deep neural networks, exploding gradients may be addressed by redesigning the network to have fewer layers.
There may also be some benefit in using a smaller batch size while training the network.
In recurrent neural networks, updating across fewer prior time steps during training, called truncated Backpropagation through time, may reduce the exploding gradient problem.

2. Use Long Short-Term Memory Networks

In recurrent neural networks, gradient exploding can occur given the inherent instability in the training of this type of network, e.g. via Backpropagation through time that essentially transforms the recurrent network into a deep multilayer Perceptron neural network.

Exploding gradients can be reduced by using the Long Short-Term Memory (LSTM) memory units and perhaps related gated-type neuron structures.
Adopting LSTM memory units is a new best practice for recurrent neural networks for sequence prediction.

3. Use Gradient Clipping

Exploding gradients can still occur in very deep Multilayer Perceptron networks with a large batch size and LSTMs with very long input sequence lengths.
If exploding gradients are still occurring, you can check for and limit the size of gradients during the training of your network.

4. Use Weight Regularization

Another approach, if exploding gradients are still occurring, is to check the size of network weights and apply a penalty to the networks loss function for large weight values.

(Using an L1 or L2 penalty on the recurrent weights can help with exploding gradients)

### Dense Layers

In [0]:
tf.keras.layers.Dense(
    units,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None
)

### Convolutional Layers

In [0]:
tf.keras.layers.Conv1D(
    filters,
    kernel_size,
    strides=1,
    padding='valid',
    data_format='channels_last',
    dilation_rate=1,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None
)

tf.keras.layers.Conv2D(
    filters,
    kernel_size,
    strides=(1, 1),
    padding='valid',
    data_format=None,
    dilation_rate=(1, 1),
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None
)

### Pooling Layers

In [0]:
tf.keras.layers.MaxPooling1D(
    pool_size=2,
    strides=None,
    padding='valid',
    data_format='channels_last'
)

tf.keras.layers.MaxPooling2D(
    pool_size=(2, 2),
    strides=None,
    padding='valid',
    data_format=None
)

tf.keras.layers.MaxPooling3D(
    pool_size=(2, 2, 2),
    strides=None,
    padding='valid',
    data_format=None
)

### Locally Connected Layers

In [0]:
tf.keras.layers.LocallyConnected1D(
    filters,
    kernel_size,
    strides=1,
    padding='valid',
    data_format=None,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    implementation=1
)

tf.keras.layers.LocallyConnected2D(
    filters,
    kernel_size,
    strides=(1, 1),
    padding='valid',
    data_format=None,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    implementation=1
)

### Flatten Layers

In [0]:
model.add(Conv2D(64, (3, 3),input_shape=(3, 32, 32), padding='same',))
# now: model.output_shape == (None, 64, 32, 32)
model.add(Flatten())
# now: model.output_shape == (None, 65536)

### Recurrent Layers

In [0]:
tf.keras.layers.RNN(
    cell,
    return_sequences=False,
    return_state=False,
    go_backwards=False,
    stateful=False,
    unroll=False,
    time_major=False
)

tf.keras.layers.SimpleRNN(
    units,
    activation='tanh',
    use_bias=True,
    kernel_initializer='glorot_uniform',
    recurrent_initializer='orthogonal',
    bias_initializer='zeros',
    kernel_regularizer=None,
    recurrent_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    recurrent_constraint=None,
    bias_constraint=None,
    dropout=0.0,
    recurrent_dropout=0.0,
    return_sequences=False,
    return_state=False,
    go_backwards=False,
    stateful=False,
    unroll=False
)

tf.keras.layers.GRU(
    units,
    activation='tanh',
    recurrent_activation='sigmoid',
    use_bias=True,
    kernel_initializer='glorot_uniform',
    recurrent_initializer='orthogonal',
    bias_initializer='zeros',
    kernel_regularizer=None,
    recurrent_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    recurrent_constraint=None,
    bias_constraint=None,
    dropout=0.0,
    recurrent_dropout=0.0,
    implementation=2,
    return_sequences=False,
    return_state=False,
    go_backwards=False,
    stateful=False,
    unroll=False,
    time_major=False,
    reset_after=True
)

tf.keras.layers.LSTM(
    units,
    activation='tanh',
    recurrent_activation='sigmoid',
    use_bias=True,
    kernel_initializer='glorot_uniform',
    recurrent_initializer='orthogonal',
    bias_initializer='zeros',
    unit_forget_bias=True,
    kernel_regularizer=None,
    recurrent_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    recurrent_constraint=None,
    bias_constraint=None,
    dropout=0.0,
    recurrent_dropout=0.0,
    implementation=2,
    return_sequences=False,
    return_state=False,
    go_backwards=False,
    stateful=False,
    time_major=False,
    unroll=False
)


### Advanced Activation Layers

In [0]:
tf.keras.layers.ReLU(max_value=None, negative_slope=0.0, threshold=0.0)
tf.keras.layers.ELU(alpha=1.0) # Fast and Accurate Deep Network Learning by Exponential Linear Units (ELUs)
tf.keras.layers.Softmax(axis=-1)
tf.keras.layers.LeakyReLU(alpha=0.3) #Rectifier Nonlinearities Improve Neural Network Acoustic Models
tf.keras.layers.PReLU(alpha_initializer='zeros', alpha_regularizer=None, alpha_constraint=None, shared_axes=None) #Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification
tf.keras.layers.ThresholdedReLU(theta=1.0) #Zero-Bias Autoencoders and the Benefits of Co-Adapting Features

### Embedding Layer - A Theoretically Grounded Application of Dropout in Recurrent Neural Networks (RNN)

In [0]:
tf.keras.layers.Embedding(input_dim, output_dim, embeddings_initializer='uniform', embeddings_regularizer=None, activity_regularizer=None, embeddings_constraint=None, mask_zero=False, input_length=None)

### Accelerating Deep Network Training (Reducing Internal Covariate Shift)

In [0]:
tf.keras.layers.BatchNormalization(
    axis=-1,
    momentum=0.99,
    epsilon=0.001,
    center=True,
    scale=True,
    beta_initializer='zeros',
    gamma_initializer='ones',
    moving_mean_initializer='zeros',
    moving_variance_initializer='ones',
    beta_regularizer=None,
    gamma_regularizer=None,
    beta_constraint=None,
    gamma_constraint=None,
    renorm=False,
    renorm_clipping=None,
    renorm_momentum=0.99,
    fused=None,
    trainable=True,
    virtual_batch_size=None,
    adjustment=None,
    name=None
)

### Prevent Overfitting

In [0]:
tf.keras.layers.Dropout(rate, noise_shape=None, seed=None, **kwargs)
tf.keras.layers.GaussianNoise(stddev)
tf.keras.layers.GaussianDropout(rate)
tf.keras.layers.AlphaDropout(rate, noise_shape=None, seed=None)

### Activation

In [0]:
tf.keras.activations.elu(x, alpha=1.0)
tf.keras.activations.exponential(x)
tf.keras.activations.hard_sigmoid(x)
tf.keras.activations.linear(x)
tf.keras.activations.relu(x, alpha=0.0, max_value=None, threshold=0)
tf.keras.activations.selu(x)
tf.keras.activations.sigmoid(x)
tf.keras.activations.tanh(x)
tf.keras.activations.softmax(x, axis=-1)
tf.keras.activations.softplus(x)
tf.keras.activations.softsign(x)

### Regularizers

In [0]:
# A linear layer with L1 regularization of factor 0.01 applied to the kernel matrix:
layers.Dense(64, kernel_regularizer=tf.keras.regularizers.l1(0.01))

# A linear layer with L2 regularization of factor 0.01 applied to the bias vector:
layers.Dense(64, bias_regularizer=tf.keras.regularizers.l2(0.01))

# A linear layer with L1 & L2 regularization of factor 0.01 applied to the kernel matrix:
layers.Dense(64, kernel_regularizer=tf.keras.regularizers.l1_l2(l1=0.01, l2=0.01))

### Metrics 

In [0]:
tf.keras.metrics.CategoricalAccuracy()
tf.keras.metrics.Accuracy()
tf.keras.metrics.AUC()
tf.keras.metrics.BinaryAccuracy()
tf.keras.metrics.BinaryCrossentropy()
tf.keras.metrics.CategoricalAccuracy()
tf.keras.metrics.CategoricalCrossentropy()
tf.keras.metrics.CategoricalHinge()
tf.keras.metrics.CosineSimilarity()
tf.keras.metrics.Hinge()

tf.keras.metrics.KLD(y_true, y_pred)
tf.keras.metrics.MAE(y_true, y_pred)
tf.keras.metrics.MAPE(y_true, y_pred)
tf.keras.metrics.Mean()
tf.keras.metrics.MSE(y_true, y_pred)
tf.keras.metrics.MSLE(y_true, y_pred)

tf.keras.metrics.Poisson()
tf.keras.metrics.RootMeanSquaredError()
tf.keras.metrics.SparseCategoricalCrossentropy()



### Loss Functions

In [0]:
tf.keras.losses.CategoricalCrossentropy(
    from_logits=False,
    label_smoothing=0,
    reduction='auto',
    name='categorical_crossentropy',
)

tf.keras.losses.BinaryCrossentropy(
    from_logits=False,
    label_smoothing=0,
    reduction='auto',
    name='binary_crossentropy',
)

tf.keras.losses.CategoricalHinge(
    reduction='auto',
    name='categorical_hinge',
)

tf.keras.losses.CosineSimilarity(
    axis=-1,
    reduction='auto',
    name='cosine_similarity',
)

tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=False,
    reduction='auto',
    name=None,
)

tf.keras.losses.KLD(y_true, y_pred)
tf.keras.losses.LogCosh(reduction='auto', name='logcosh')
tf.keras.losses.Poisson(reduction='auto', name='poisson')
tf.keras.losses.SquaredHinge(reduction='auto', name='squared_hinge')

tf.keras.losses.MAE(y_true, y_pred)
tf.keras.losses.MAPE(y_true, y_pred)
tf.keras.losses.MSE(y_true, y_pred)
tf.keras.losses.MSLE(y_true, y_pred)

### Optimizers

In [0]:
tf.keras.optimizers.Adadelta(
    learning_rate=0.001,
    rho=0.95,
    epsilon=1e-07,
    name='Adadelta'
)

tf.keras.optimizers.Adagrad(
    learning_rate=0.001,
    initial_accumulator_value=0.1,
    epsilon=1e-07,
    name='Adagrad'
)

tf.keras.optimizers.Adam(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False,
    name='Adam'
)

tf.keras.optimizers.Adamax(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    name='Adamax'
)

tf.keras.optimizers.Nadam(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    name='Nadam'
)

tf.keras.optimizers.SGD(
    learning_rate=0.01,
    momentum=0.0,
    nesterov=False,
    name='SGD'
)

tf.keras.optimizers.Ftrl(
    learning_rate=0.001,
    learning_rate_power=-0.5,
    initial_accumulator_value=0.1,
    l1_regularization_strength=0.0,
    l2_regularization_strength=0.0,
    name='Ftrl',
    l2_shrinkage_regularization_strength=0.0
)

##TensorFlow (Basic Architectures)

Sequential Models

### Deep Neural Networks (DNN)

#### Deep Neural Network (DNN) for Regression :

In [0]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras import regularizers
import tensorflow.keras.backend as K

K.clear_session()

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir='./Graph', histogram_freq=1)


tensorboard = tf.keras.callbacks.TensorBoard(log_dir='./Graph',
                                 write_graph=True,
                                 histogram_freq=1)

def root_mean_squared_error(y_true, y_pred):
        return K.sqrt(K.mean(K.square(y_pred - y_true), axis=-1)) 

def regression_model() :   
    model = tf.keras.Sequential()
    model.add(layers.Dense(64,input_dim=4))
    model.add(layers.Dense(32,activation=tf.nn.relu))
    model.add(layers.Dense(16,activation=tf.nn.relu))
    model.add(layers.Dense(1))
    
    model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),loss = "mse",metrics =["accuracy"])
    
    return model


model = regression_model()
model.fit(X_train,y_train,epochs=100,batch_size=1024,validation_data=(X_test,y_test),callbacks=[tensorboard_callback])
y_pred = model.predict(X_test)
y_pred

Train on 14480 samples, validate on 7133 samples
Epoch 1/100
14480/14480 [==============================] - 0s 15us/sample - loss: 24077.8424 - acc: 0.0854 - val_loss: 0.0215 - val_acc: 0.9867
Epoch 2/100
14480/14480 [==============================] - 0s 7us/sample - loss: 0.0125 - acc: 0.9927 - val_loss: 0.0129 - val_acc: 0.9909
Epoch 3/100
14480/14480 [==============================] - 0s 6us/sample - loss: 0.0130 - acc: 0.9927 - val_loss: 0.0827 - val_acc: 0.9256
Epoch 4/100
14480/14480 [==============================] - 0s 6us/sample - loss: 885.8289 - acc: 0.5742 - val_loss: 1.7083 - val_acc: 0.9912
Epoch 5/100
14480/14480 [==============================] - 0s 7us/sample - loss: 529.4218 - acc: 0.5157 - val_loss: 524.7122 - val_acc: 0.0088
Epoch 6/100
14480/14480 [==============================] - 0s 6us/sample - loss: 445.0928 - acc: 0.4961 - val_loss: 778.1347 - val_acc: 0.9912
Epoch 7/100
14480/14480 [==============================] - 0s 6us/sample - loss: 489.3062 - acc: 0.504

array([[0.00735136],
       [0.00735136],
       [0.00735136],
       ...,
       [0.00735136],
       [0.00735136],
       [0.00735136]], dtype=float32)

#### Deep Neural Network (DNN) for Binary Classification :

In [0]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras import regularizers
import tensorflow.keras.backend as K

K.clear_session()

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir='./Graph', histogram_freq=1)


tensorboard = tf.keras.callbacks.TensorBoard(log_dir='./Graph',
                                 write_graph=True,
                                 histogram_freq=1)

def root_mean_squared_error(y_true, y_pred):
        return K.sqrt(K.mean(K.square(y_pred - y_true), axis=-1)) 

def binaryclass_model() :   
    model = tf.keras.Sequential()
    model.add(layers.Dense(128,input_dim=4))
    model.add(layers.Dense(64,activation=tf.nn.relu))
    model.add(layers.Dense(32,activation=tf.nn.relu))
    model.add(layers.Dense(1,activation=tf.nn.sigmoid))  
    
    model.compile(optimizer=tf.keras.optimizers.RMSprop(0.01),loss = 'binary_crossentropy',metrics =["accuracy"])

    return model


model = binaryclass_model()
model.fit(X_train,y_train,epochs=100,batch_size=1024,validation_data=(X_test,y_test),callbacks=[tensorboard_callback])
y_pred = model.predict(X_test)
y_pred

Train on 14480 samples, validate on 7133 samples
Epoch 1/100
14480/14480 [==============================] - 1s 39us/sample - loss: 8295368.5436 - accuracy: 0.0000e+00 - val_loss: 8402822.8707 - val_accuracy: 0.0000e+00
Epoch 2/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.2729 - accuracy: 0.0000e+00 - val_loss: 8402822.3857 - val_accuracy: 0.0000e+00
Epoch 3/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.4691 - accuracy: 0.0000e+00 - val_loss: 8402822.7523 - val_accuracy: 0.0000e+00
Epoch 4/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.4298 - accuracy: 0.0000e+00 - val_loss: 8402822.7397 - val_accuracy: 0.0000e+00
Epoch 5/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.2298 - accuracy: 0.0000e+00 - val_loss: 8402822.7931 - val_accuracy: 0.0000e+00
Epoch 6/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.6033 - accuracy:

Epoch 49/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.4177 - accuracy: 0.0000e+00 - val_loss: 8402822.4830 - val_accuracy: 0.0000e+00
Epoch 50/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.5586 - accuracy: 0.0000e+00 - val_loss: 8402822.9157 - val_accuracy: 0.0000e+00
Epoch 51/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.4431 - accuracy: 0.0000e+00 - val_loss: 8402822.5925 - val_accuracy: 0.0000e+00
Epoch 52/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.3072 - accuracy: 0.0000e+00 - val_loss: 8402822.5470 - val_accuracy: 0.0000e+00
Epoch 53/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.3116 - accuracy: 0.0000e+00 - val_loss: 8402822.5311 - val_accuracy: 0.0000e+00
Epoch 54/100
14480/14480 [==============================] - 0s 8us/sample - loss: 8295368.3536 - accuracy: 0.0000e+00 - val_loss: 8402822.7465 - val_a

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

#### Deep Neural Network (DNN) for Multi-Class Classification :

In [0]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras import regularizers
import tensorflow.keras.backend as K

K.clear_session()

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir='./Graph', histogram_freq=1)


tensorboard = tf.keras.callbacks.TensorBoard(log_dir='./Graph',
                                 write_graph=True,
                                 histogram_freq=1)

def root_mean_squared_error(y_true, y_pred):
        return K.sqrt(K.mean(K.square(y_pred - y_true), axis=-1)) 

def multiclass_model() :   
    model = tf.keras.Sequential()
    model.add(layers.Dense(128,input_dim=4))
    model.add(layers.Dense(64,activation=tf.nn.relu))
    model.add(layers.Dense(32,activation=tf.nn.relu))
    model.add(layers.Dense(14,activation=tf.nn.softmax))  
    
    model.compile(optimizer=tf.keras.optimizers.RMSprop(0.01),loss = 'sparse_categorical_crossentropy',metrics =["accuracy"])
    
    return model


model = multiclass_model()
model.fit(X_train,y_train,epochs=100,batch_size=1024,validation_data=(X_test,y_test),callbacks=[tensorboard_callback])
y_pred = model.predict(X_test)
y_pred

Train on 14480 samples, validate on 7133 samples
Epoch 1/100
14480/14480 [==============================] - 1s 37us/sample - loss: 85.2323 - acc: 0.7825 - val_loss: 18.4541 - val_acc: 0.9912
Epoch 2/100
14480/14480 [==============================] - 0s 27us/sample - loss: 10.4217 - acc: 0.9931 - val_loss: 11.4321 - val_acc: 0.9912
Epoch 3/100
14480/14480 [==============================] - 0s 29us/sample - loss: 5.5147 - acc: 0.9231 - val_loss: 17.2698 - val_acc: 0.9912
Epoch 4/100
14480/14480 [==============================] - 0s 31us/sample - loss: 7.8217 - acc: 0.9931 - val_loss: 5.1975 - val_acc: 0.9912
Epoch 5/100
14480/14480 [==============================] - 0s 30us/sample - loss: 36.9202 - acc: 0.8541 - val_loss: 19.9685 - val_acc: 0.9912
Epoch 6/100
14480/14480 [==============================] - 0s 28us/sample - loss: 10.7934 - acc: 0.9931 - val_loss: 10.4356 - val_acc: 0.9912
Epoch 7/100
14480/14480 [==============================] - 0s 28us/sample - loss: 8.3069 - acc: 0.9231

array([[9.9342322e-01, 6.5678796e-03, 7.1360387e-07, ..., 7.6804082e-07,
        7.7093949e-07, 7.5853711e-07],
       [9.9342322e-01, 6.5678796e-03, 7.1360387e-07, ..., 7.6804082e-07,
        7.7093949e-07, 7.5853711e-07],
       [9.9342322e-01, 6.5678796e-03, 7.1360387e-07, ..., 7.6804082e-07,
        7.7093949e-07, 7.5853711e-07],
       ...,
       [9.9342322e-01, 6.5678796e-03, 7.1360387e-07, ..., 7.6804082e-07,
        7.7093949e-07, 7.5853711e-07],
       [9.9342322e-01, 6.5678796e-03, 7.1360387e-07, ..., 7.6804082e-07,
        7.7093949e-07, 7.5853711e-07],
       [9.9342322e-01, 6.5678796e-03, 7.1360387e-07, ..., 7.6804076e-07,
        7.7093949e-07, 7.5853706e-07]], dtype=float32)

### Convolutional Neural Network (CNN)

#### Convolutional Neural Network (CNN) for Multi-Class Classification :

In [0]:
import numpy as np
import keras
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD

X_train = np.random.random((100, 100, 100, 3))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)
X_test = np.random.random((20, 100, 100, 3))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(20, 1)), num_classes=10)

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

def cnn_model() :   
    model = tf.keras.Sequential()
    
# input: 100x100 images with 3 channels -> (100, 100, 3) tensors.
# this applies 32 convolution filters of size 3x3 each.

    model.add(layers.Conv2D(32, (3, 3), activation=tf.nn.relu, input_shape=(100, 100, 3)))
    model.add(layers.Conv2D(32, (3, 3), activation=tf.nn.relu))
    model.add(layers.MaxPooling2D(pool_size=(2, 2)))
    model.add(layers.Dropout(0.25))
    
    model.add(layers.Conv2D(64, (3, 3), activation=tf.nn.relu))
    model.add(layers.Conv2D(64, (3, 3), activation=tf.nn.relu))
    model.add(layers.MaxPooling2D(pool_size=(2, 2)))
    model.add(layers.Dropout(0.25))

    model.add(layers.Flatten())
    model.add(layers.Dense(256, activation=tf.nn.relu))
    model.add(layers.Dropout(0.5))
    model.add(layers.Dense(10, activation=tf.nn.softmax))

    
    model.compile(loss='categorical_crossentropy', optimizer=sgd)

    return model

model = cnn_model()
model.fit(X_train, y_train, batch_size=32, epochs=10)
score = model.evaluate(X_test, y_test, batch_size=32)

Using TensorFlow backend.


Epoch 1/10
100/100 [==============================] - 5s 50ms/sample - loss: 2.2897
Epoch 2/10
100/100 [==============================] - 5s 48ms/sample - loss: 2.3151
Epoch 3/10
100/100 [==============================] - 5s 48ms/sample - loss: 2.3100
Epoch 4/10
100/100 [==============================] - 5s 48ms/sample - loss: 2.2882
Epoch 5/10
100/100 [==============================] - 5s 48ms/sample - loss: 2.2574
Epoch 6/10
100/100 [==============================] - 5s 48ms/sample - loss: 2.3003
Epoch 7/10
100/100 [==============================] - 5s 48ms/sample - loss: 2.2794
Epoch 8/10
100/100 [==============================] - 5s 49ms/sample - loss: 2.2688
Epoch 9/10
100/100 [==============================] - 5s 48ms/sample - loss: 2.2722
Epoch 10/10
20/20 [==============================] - 0s 15ms/sample - loss: 2.3009


### Recurrent Neural Network (LSTM)

#### Recurrent Neural Network (LSTM) for Regression:

In [0]:
X_train = np.array(X_train)
y_train = np.array(y_train)

X_test = np.array(X_test)
y_test = np.array(y_test)

print (X_train.shape)
print (y_train.shape)
print (X_test.shape)
print (y_test.shape)

X_train = X_train.reshape(X_train.shape[0],1,X_train.shape[1])
X_test = X_test.reshape(X_test.shape[0],1,X_test.shape[1])

print (X_train.shape)
print (y_train.shape)
print (X_test.shape)
print (y_test.shape)

(14480, 4)
(14480,)
(7133, 4)
(7133,)
(14480, 1, 4)
(14480,)
(7133, 1, 4)
(7133,)


In [0]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras import regularizers
import tensorflow.keras.backend as K

K.clear_session()

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir='./Graph', histogram_freq=1)


tensorboard = tf.keras.callbacks.TensorBoard(log_dir='./Graph',
                                 write_graph=True,
                                 histogram_freq=1)

def root_mean_squared_error(y_true, y_pred):
        return K.sqrt(K.mean(K.square(y_pred - y_true), axis=-1)) 

def lstm_model() :   
    model = tf.keras.Sequential()
    model.add(layers.LSTM(128,input_shape=(X_train.shape[1], X_train.shape[2]),return_sequences=True))
    model.add(layers.Dropout(0.25))
    model.add(layers.LSTM(32))
    model.add(layers.Dense(1))  
    
    model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),loss = "mse",metrics =["accuracy"])
    
    return model


model = lstm_model()
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),callbacks=[tensorboard_callback])
y_pred = model.predict(X_test)
y_pred

W0616 17:49:14.839148 140373151274880 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 14480 samples, validate on 7133 samples
Epoch 1/10
14480/14480 [==============================] - 7s 481us/sample - loss: 416599474139.7923 - acc: 0.0000e+00 - val_loss: 446471973033.6857 - val_acc: 0.0000e+00
Epoch 2/10
14480/14480 [==============================] - 5s 365us/sample - loss: 416586449457.2199 - acc: 0.0000e+00 - val_loss: 446459547576.2209 - val_acc: 0.0000e+00
Epoch 3/10
14480/14480 [==============================] - 5s 354us/sample - loss: 416574177243.7923 - acc: 0.0000e+00 - val_loss: 446447106407.7567 - val_acc: 0.0000e+00
Epoch 4/10
14480/14480 [==============================] - 5s 360us/sample - loss: 416561902025.1227 - acc: 0.0000e+00 - val_loss: 446434691070.5644 - val_acc: 0.0000e+00
Epoch 5/10
14480/14480 [==============================] - 5s 359us/sample - loss: 416549629775.4873 - acc: 0.0000e+00 - val_loss: 446422231067.2761 - val_acc: 0.0000e+00
Epoch 6/10
14480/14480 [==============================] - 5s 352us/sample - loss: 416537372769.3083 -

array([[119.00605],
       [119.00605],
       [119.00605],
       ...,
       [119.00605],
       [119.00605],
       [119.00605]], dtype=float32)

## Keras Functional API (Complex Architectures)

The Keras functional API lets you build much more complex architectures than the simple linear stack of Sequential models we have seen previously. It also supports more advanced models. These models include multi-input and multi-output models, models with shared layers, and models with residual connections

In [0]:
import tensorflow as tf

inputs = tf.keras.Input(shape=(4,)) # Returns a 'placeholder' tensor
x = tf.keras.layers.Dense(128)(inputs)
x = tf.keras.layers.Dense(64, activation='relu',name='d1')(x)
x = tf.keras.layers.Dense(32, activation='relu',name='d2')(x)
x = tf.keras.layers.Dense(16, activation='relu',name='d3')(x)
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(14,activation=tf.nn.softmax, name='d4')(x)

model = tf.keras.Model(inputs=inputs, outputs=predictions)

In [0]:
optimiser = tf.keras.optimizers.RMSprop(0.01)
model.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit(X_train, y_train, batch_size=512, epochs=10)
model.evaluate(X_test,y_test)

Epoch 1/10
14480/14480 [==============================] - 0s 18us/sample - loss: 79.3885 - acc: 0.2677
Epoch 2/10
14480/14480 [==============================] - 0s 10us/sample - loss: 2.2260 - acc: 0.4157
Epoch 3/10
14480/14480 [==============================] - 0s 9us/sample - loss: 1.9951 - acc: 0.4157
Epoch 4/10
14480/14480 [==============================] - 0s 10us/sample - loss: 1.8234 - acc: 0.4157
Epoch 5/10
14480/14480 [==============================] - 0s 9us/sample - loss: 1.7056 - acc: 0.4157
Epoch 6/10
14480/14480 [==============================] - 0s 9us/sample - loss: 1.6299 - acc: 0.4157
Epoch 7/10
14480/14480 [==============================] - 0s 8us/sample - loss: 1.5845 - acc: 0.4157
Epoch 8/10
14480/14480 [==============================] - 0s 9us/sample - loss: 1.5578 - acc: 0.4157
Epoch 9/10
14480/14480 [==============================] - 0s 9us/sample - loss: 1.5430 - acc: 0.4157
Epoch 10/10
7133/7133 [==============================] - 0s 70us/sample - loss: 1.5369 

[1.5368850278968014, 0.41525304]